
project_id = "rmxzryueysmzksmvpwpv"

[functions.update-lead]
verify_jwt = false

[functions.notify-slack]
verify_jwt = false

[functions.create-works-lead]
verify_jwt = false

[functions.notify-works-slack]
verify_jwt = false
