import { useMemo, useState } from "react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import {
  ArrowRight, BadgeCheck, BarChart3, BookOpen, ChefHat, ChevronDown,
  CircleDollarSign, ClipboardList, FileText, Landmark, LineChart,
  Link2, PackageCheck, ReceiptText, ShoppingBasket, Store,
  UsersRound, UtensilsCrossed,
} from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

type SortKey = "margin" | "sales" | "cost";
type Dish = { name: string; category: string; price: number; cost: number; sales: number; avocadoWeight: number };

const exampleDishes: readonly Dish[] = [
  { name: "Ensalada de palta", category: "Ensaladas", price: 10900, cost: 3560, sales: 186, avocadoWeight: 0.36 },
  { name: "Salmón a la plancha", category: "Fondos", price: 14900, cost: 6220, sales: 118, avocadoWeight: 0 },
  { name: "Hamburguesa de la casa", category: "Fondos", price: 11900, cost: 4310, sales: 242, avocadoWeight: 0.08 },
  { name: "Tártaro de atún", category: "Entradas", price: 9900, cost: 3840, sales: 76, avocadoWeight: 0.18 },
  { name: "Risotto de hongos", category: "Fondos", price: 10800, cost: 4720, sales: 91, avocadoWeight: 0 },
  { name: "Ceviche clásico", category: "Entradas", price: 9800, cost: 3990, sales: 154, avocadoWeight: 0.14 },
];

const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
const whatsapp = "https://api.whatsapp.com/send/?phone=56932595791&text=Hola%20Ruka%2C%20quiero%20conocer%20el%20panel%20de%20food%20cost.";

function DataSource({ icon: Icon, title, detail }: { icon: typeof Store; title: string; detail: string }) {
  return <div className="flex min-w-0 items-center gap-3 rounded-xl border border-[#dde3ee] bg-white px-3 py-3 shadow-[0_8px_20px_rgba(32,39,64,0.04)]"><span className="flex h-9 w-9 flex-none items-center justify-center rounded-lg bg-[#eef1ff] text-primary"><Icon className="h-4 w-4" /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-[#27334d]">{title}</span><span className="block truncate text-xs text-[#717c91]">{detail}</span></span></div>;
}

function DishCard() {
  return <div className="relative mx-auto w-full max-w-[31rem] overflow-hidden rounded-[28px] border border-[#dce1eb] bg-white p-4 shadow-[0_24px_70px_rgba(24,30,52,0.13)] sm:p-5">
    <div className="flex items-center justify-between gap-3 border-b border-[#e8ebf2] pb-3"><div className="flex items-center gap-2 text-xs font-semibold text-[#687080]"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#eef1ff] text-primary"><UtensilsCrossed className="h-4 w-4" /></span>Ficha de plato · datos de ejemplo</div><span className="rounded-full bg-[#eaf9f3] px-2.5 py-1 text-xs font-semibold text-[#16815e]">Margen saludable</span></div>
    <div className="grid grid-cols-[7rem_minmax(0,1fr)] gap-4 py-5 sm:grid-cols-[8.5rem_minmax(0,1fr)]"><div className="relative aspect-square self-center rounded-full border-[9px] border-[#f5f6fa] bg-[#e7edf6] shadow-inner"><div className="absolute inset-[14%] rounded-full bg-[#96bd65]" /><div className="absolute left-[20%] top-[20%] h-[34%] w-[34%] rounded-full bg-[#e3be62]" /><div className="absolute bottom-[17%] right-[18%] h-[38%] w-[38%] rounded-full bg-[#d87957]" /><div className="absolute inset-[31%] rounded-full border-[5px] border-white/75" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">Ensalada de palta</p><p className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-[#171827]">67,3%</p><p className="mt-1 text-sm text-[#667085]">margen bruto hoy</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-[#f7f8fc] p-2.5"><p className="text-[11px] font-medium text-[#778198]">Precio</p><p className="mt-1 text-sm font-semibold text-[#25314a]">$10.900</p></div><div className="rounded-lg bg-[#f7f8fc] p-2.5"><p className="text-[11px] font-medium text-[#778198]">Costo real</p><p className="mt-1 text-sm font-semibold text-[#25314a]">$3.560</p></div></div></div></div>
    <div className="rounded-xl border border-[#d9e0f2] bg-[#f8f9ff] px-3 py-3"><div className="flex items-center justify-between gap-2 text-sm"><span className="font-medium text-[#3d4960]">Palta subió 12%</span><span className="font-semibold text-[#c66b37]">−1,6 pts margen</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#dce3f0]"><div className="h-full w-[67%] rounded-full bg-primary" /></div></div>
  </div>;
}

type CalculatedDish = Dish & { adjustedCost: number; margin: number };

function Quadrant({ title, hint, dishes, tone }: { title: string; hint: string; dishes: readonly CalculatedDish[]; tone: string }) {
  return <div className="rounded-xl border border-[#e0e5ef] bg-white p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold text-[#293650]">{title}</p><span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${tone}`}>{dishes.length}</span></div><p className="mt-1 text-xs text-[#778198]">{hint}</p><div className="mt-3 space-y-1.5">{dishes.slice(0, 2).map((dish) => <div key={dish.name} className="flex items-center justify-between gap-2 text-xs"><span className="truncate font-medium text-[#506079]">{dish.name}</span><span className="font-semibold text-[#34425c]">{dish.margin.toFixed(0)}%</span></div>)}{dishes.length === 0 ? <p className="text-xs text-[#9aa3b3]">Sin platos en este grupo</p> : null}</div></div>;
}

function Matrix({ dishes, avocadoIncrease, onIncrease, sortKey, onSort }: { dishes: readonly CalculatedDish[]; avocadoIncrease: number; onIncrease: (value: number) => void; sortKey: SortKey; onSort: (value: SortKey) => void }) {
  const stars = dishes.filter((dish) => dish.margin >= 62 && dish.sales >= 120);
  const opportunities = dishes.filter((dish) => dish.margin >= 62 && dish.sales < 120);
  const anchors = dishes.filter((dish) => dish.margin < 62 && dish.sales >= 120);
  const review = dishes.filter((dish) => dish.margin < 62 && dish.sales < 120);
  return <section className="rounded-[24px] border border-[#dce1eb] bg-[#f7f8fc] p-4 shadow-[0_18px_50px_rgba(24,30,52,0.06)] sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-primary">Datos de ejemplo</p><h3 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-[#1b2335]">Matriz de carta: margen y popularidad.</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-[#657087]">Ordena los platos y simula cómo un cambio de costo afecta la carta antes de que llegue al cierre de mes.</p></div><label className="rounded-xl border border-[#dbe1ee] bg-white px-4 py-3 text-sm text-[#46536b]">Ordenar por <select value={sortKey} onChange={(event) => onSort(event.target.value as SortKey)} className="ml-2 bg-transparent font-semibold text-[#2d3a55] outline-none"><option value="margin">Margen</option><option value="sales">Ventas</option><option value="cost">Costo</option></select></label></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(17rem,0.8fr)]"><div className="overflow-hidden rounded-xl border border-[#dbe1ec] bg-white"><div className="grid grid-cols-[minmax(10rem,1.4fr)_0.7fr_0.7fr_0.7fr] gap-2 border-b border-[#e8ebf2] bg-[#fbfcff] px-4 py-3 text-[11px] font-semibold uppercase tracking-[0.09em] text-[#7b8699]"><span>Plato</span><span className="text-right">Costo</span><span className="text-right">Margen</span><span className="text-right">Ventas</span></div><div className="divide-y divide-[#edf0f5]">{dishes.map((dish) => <div key={dish.name} className="grid grid-cols-[minmax(10rem,1.4fr)_0.7fr_0.7fr_0.7fr] items-center gap-2 px-4 py-3 text-sm"><div className="min-w-0"><p className="truncate font-semibold text-[#31405b]">{dish.name}</p><p className="truncate text-xs text-[#7b879a]">{dish.category}</p></div><span className="text-right text-[#56637b]">{money.format(dish.adjustedCost)}</span><span className={`text-right font-semibold ${dish.margin < 60 ? "text-[#c65355]" : "text-[#16815e]"}`}>{dish.margin.toFixed(1)}%</span><span className="text-right font-medium text-[#45536d]">{dish.sales}</span></div>)}</div></div><div className="grid grid-cols-2 gap-3"><Quadrant title="Estrellas" hint="alto margen · alta venta" dishes={stars} tone="bg-[#eaf9f3] text-[#16815e]" /><Quadrant title="Oportunidades" hint="alto margen · baja venta" dishes={opportunities} tone="bg-[#eef1ff] text-primary" /><Quadrant title="Anclas" hint="bajo margen · alta venta" dishes={anchors} tone="bg-[#fff5e8] text-[#ad7017]" /><Quadrant title="Revisar" hint="bajo margen · baja venta" dishes={review} tone="bg-[#fff0f3] text-[#c65355]" /></div></div>
    <div className="mt-5 rounded-xl border border-[#dce2f1] bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-[#35415a]">Simular alza de palta</p><p className="mt-1 text-xs text-[#758097]">Afecta solo los platos que incluyen palta en esta carta de ejemplo.</p></div><span className="rounded-full bg-[#f7f8fc] px-3 py-1.5 text-sm font-semibold text-primary">+{avocadoIncrease}%</span></div><input aria-label="Alza de costo de palta" type="range" min="0" max="40" step="2" value={avocadoIncrease} onChange={(event) => onIncrease(Number(event.target.value))} className="mt-4 h-2 w-full cursor-pointer accent-primary" /></div>
  </section>;
}

const faqs = [
  ["¿Necesito cargar mis recetas y precios a mano?", "Ruka puede trabajar con la carta, recetas y fuentes de compra que ya usa tu operación. La configuración del piloto define qué información se conecta y cómo se relaciona."],
  ["¿Con qué POS puede trabajar?", "La integración depende de las fuentes disponibles en tu operación. Hoy la página muestra Toteat, Fudo, Justo, Kame, Defontana, Gourmedia y SII como referencias de alcance."],
  ["¿El costo cambia cuando cambia una factura?", "El objetivo del flujo es relacionar las compras reales con la carta. El comportamiento exacto depende de la configuración, las recetas y las reglas acordadas para tu operación."],
  ["¿Reemplaza mi ERP o mi software de restaurante?", "No. Ruka conecta y prepara información entre las herramientas existentes para que el equipo pueda decidir con datos actualizados."],
  ["¿Qué necesitamos para empezar?", "Una conversación sobre tu carta, tus ventas y cómo llegan tus facturas de compra. Con eso se puede evaluar el alcance del piloto."],
] as const;

export default function PanelControl() {
  const [sortKey, setSortKey] = useState<SortKey>("margin");
  const [avocadoIncrease, setAvocadoIncrease] = useState(12);
  const dishes = useMemo(() => exampleDishes.map((dish) => {
    const adjustedCost = dish.cost * (1 + (avocadoIncrease / 100) * dish.avocadoWeight);
    return { ...dish, adjustedCost, margin: ((dish.price - adjustedCost) / dish.price) * 100 };
  }).sort((left, right) => sortKey === "margin" ? right.margin - left.margin : sortKey === "sales" ? right.sales - left.sales : right.adjustedCost - left.adjustedCost), [avocadoIncrease, sortKey]);

  return <div className="min-h-screen bg-white text-[#20283a]"><Helmet><title>Food cost para restaurantes y costo por plato | Ruka</title><meta name="description" content="Ruka cruza ventas de POS y facturas de compra reales para mostrar el costo por plato y el margen de tu carta actualizado." /><meta name="keywords" content="food cost restaurante, costo por plato, escandallo, margen restaurante, facturas de compra, POS restaurante" /><link rel="canonical" href="https://www.ruka.ai/productos/panel-control" /><meta property="og:title" content="Cuánto te deja cada plato, actualizado solo | Ruka" /><meta property="og:description" content="Ruka cruza ventas de POS con facturas de compra reales para mantener el costo de tu carta actualizado." /><meta property="og:url" content="https://www.ruka.ai/productos/panel-control" /><meta property="og:type" content="website" /><script type="application/ld+json">{JSON.stringify({ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Ruka Panel de Control", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: "Herramienta para relacionar ventas, facturas de compra y costos por plato en restaurantes." })}</script></Helmet><Navbar />
    <main>
      <section className="overflow-hidden bg-[#f7f8fc] pb-16 pt-28 sm:pb-24 sm:pt-36"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[minmax(0,1fr)_minmax(26rem,0.9fr)] lg:items-center"><div className="max-w-2xl"><p className="inline-flex rounded-full bg-[#eef1ff] px-3 py-1.5 text-sm font-semibold text-primary">Food cost para restaurantes</p><h1 className="mt-6 text-balance text-5xl font-semibold leading-[0.98] tracking-[-0.055em] text-[#171827] sm:text-6xl">Cuánto te deja cada plato, actualizado solo.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#586177]">Ruka cruza las ventas de tu POS con tus facturas de compra reales. Cuando sube la palta, el costo de tu ensalada cambia ese mismo día.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="inline-flex items-center justify-center rounded-full bg-primary px-5 py-3.5 text-sm font-semibold text-white shadow-[0_12px_24px_rgba(80,97,227,0.22)] transition-transform hover:-translate-y-0.5">Agendar una conversación <ArrowRight className="ml-2 h-4 w-4" /></Link><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-[#cfd6e5] bg-white px-5 py-3.5 text-sm font-semibold text-[#33405a] transition-colors hover:bg-[#f7f8fc]">Hablar por WhatsApp</a></div><p className="mt-4 text-sm text-[#758096]">Datos de ejemplo para mostrar cómo se ve el cruce.</p></div><DishCard /></div></section>
      <section className="border-y border-[#e4e8f0] bg-white py-7"><div className="mx-auto grid max-w-7xl gap-3 px-6 sm:grid-cols-2 lg:grid-cols-4"><DataSource icon={Store} title="Ventas POS" detail="Qué platos se venden" /><DataSource icon={ReceiptText} title="Facturas de compra" detail="Cuánto costaron de verdad" /><DataSource icon={BookOpen} title="Carta y recetas" detail="Qué lleva cada plato" /><DataSource icon={LineChart} title="Margen vivo" detail="Qué deja cada venta" /></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-semibold text-primary">El problema</p><h2 className="mt-3 text-balance text-4xl font-semibold leading-[1.05] tracking-[-0.045em] text-[#171827]">No te faltan datos. Te falta el cruce.</h2><p className="mt-5 text-lg leading-8 text-[#5b657a]">Tu POS sabe cuánto vendiste. El SII y tus facturas saben cuánto pagaste. Pero si esas fuentes no se relacionan, el margen de cada plato sigue siendo una estimación.</p></div><div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div className="space-y-3"><DataSource icon={Store} title="POS" detail="Ventas por plato" /><DataSource icon={FileText} title="SII y facturas" detail="Compras reales" /></div><ArrowRight className="mx-auto h-6 w-6 rotate-90 text-primary sm:rotate-0" /><div className="rounded-2xl border border-[#cfd7ff] bg-[#f3f5ff] p-5"><BadgeCheck className="h-7 w-7 text-primary" /><p className="mt-4 text-lg font-semibold text-[#263352]">Costo vivo por plato</p><p className="mt-2 text-sm leading-6 text-[#627097]">El dato que ayuda a decidir precio, carta y compra con contexto.</p></div></div></div></section>
      <section className="bg-[#f7f8fc] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-6"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">La prueba</p><h2 className="mt-3 text-balance text-4xl font-semibold leading-[1.05] tracking-[-0.045em] text-[#171827]">Mira la carta como una decisión de negocio.</h2><p className="mt-5 text-lg leading-8 text-[#5b657a]">Explora una carta de ejemplo. La simulación muestra cómo una variación de insumo cambia el costo y margen de los platos que lo incluyen.</p></div><div className="mt-10"><Matrix dishes={dishes} avocadoIncrease={avocadoIncrease} onIncrease={setAvocadoIncrease} sortKey={sortKey} onSort={setSortKey} /></div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-6"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Cómo funciona</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em] text-[#171827]">Tres pasos sobre la operación que ya tienes.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["01", PackageCheck, "Conecta las fuentes", "Revisamos la carta, las ventas y cómo llegan las compras para definir el alcance."], ["02", Link2, "Relaciona el costo real", "Ruka cruza los documentos disponibles con las reglas y recetas acordadas."], ["03", CircleDollarSign, "Revisa variaciones", "El equipo ve los cambios que merecen una decisión, con el contexto del plato y su costo."]].map(([number, Icon, title, description]) => { const StepIcon = Icon as typeof PackageCheck; return <article key={number as string} className="rounded-2xl border border-[#dfe4ed] bg-white p-6"><p className="text-sm font-semibold text-primary">{number as string}</p><span className="mt-7 flex h-11 w-11 items-center justify-center rounded-xl bg-[#eef1ff] text-primary"><StepIcon className="h-5 w-5" /></span><h3 className="mt-5 text-xl font-semibold text-[#25314a]">{title as string}</h3><p className="mt-3 leading-7 text-[#687389]">{description as string}</p></article>; })}</div></div></section>
      <section className="bg-[#f7f8fc] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-6"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Una vista por rol</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em] text-[#171827]">Cada equipo llega a una decisión distinta.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[UsersRound, "Dueño", "Ve qué platos sostienen el resultado y cuáles lo erosionan."], [ChefHat, "Chef", "Contrasta receta, costo y compra antes de ajustar una preparación."], [Landmark, "Controller", "Revisa márgenes, variaciones y documentos que requieren seguimiento."], [ShoppingBasket, "Cadena", "Compara locales y carta para encontrar diferencias operativas."]].map(([Icon, role, copy]) => { const RoleIcon = Icon as typeof UsersRound; return <article key={role as string} className="rounded-2xl border border-[#dfe4ed] bg-white p-5"><RoleIcon className="h-5 w-5 text-primary" /><h3 className="mt-5 text-lg font-semibold text-[#2b3852]">{role as string}</h3><p className="mt-2 text-sm leading-6 text-[#6b768b]">{copy as string}</p></article>; })}</div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-sm font-semibold text-primary">Lo que ya está adentro</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em] text-[#171827]">Datos que normalmente viven separados.</h2><p className="mt-5 text-lg leading-8 text-[#5b657a]">El alcance concreto se define en la conversación inicial. Estas son las piezas que el flujo puede conectar según tu operación.</p></div><div className="grid grid-cols-2 gap-3">{[[Store, "Ventas y POS"], [ReceiptText, "Facturas de compra"], [ClipboardList, "Carta y recetas"], [BarChart3, "Márgenes y reportes"], [ShoppingBasket, "Insumos y proveedores"], [FileText, "Documentos tributarios"]].map(([Icon, label]) => { const DataIcon = Icon as typeof Store; return <div key={label as string} className="flex items-center gap-3 rounded-xl border border-[#dfe4ed] bg-[#fbfcff] p-4"><DataIcon className="h-5 w-5 text-primary" /><span className="text-sm font-semibold text-[#46536b]">{label as string}</span></div>; })}</div></div></section>
      <section className="border-y border-[#e4e8f0] bg-[#f7f8fc] py-20"><div className="mx-auto max-w-7xl px-6"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Integraciones</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em] text-[#171827]">Conéctate con la operación que ya funciona.</h2></div><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{["Toteat", "Fudo", "Justo", "Kame", "Defontana", "Gourmedia", "SII"].map((name) => <div key={name} className="flex min-h-20 items-center justify-center rounded-xl border border-[#dce2ed] bg-white px-3 text-center text-sm font-semibold text-[#4a5872]">{name}</div>)}</div><p className="mt-5 text-sm text-[#748096]">La disponibilidad y forma de conexión se revisan según las fuentes de cada operación.</p></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-4xl px-6"><div className="rounded-[28px] border border-[#d8def0] bg-[#f8f9ff] p-7 text-center shadow-[0_18px_50px_rgba(24,30,52,0.07)] sm:p-10"><p className="text-sm font-semibold text-primary">Producto complementario</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-[#171827]">Se activa sobre tu plan de Ruka.</h2><p className="mx-auto mt-3 max-w-2xl text-lg text-[#5e6980]">El plan cubre el volumen de facturas que procesa Ruka. El alcance de este producto se define según tu operación.</p><Link to="/precios" className="mt-7 inline-flex items-center rounded-full bg-[#171827] px-5 py-3 text-sm font-semibold text-white">Ver planes <ArrowRight className="ml-2 h-4 w-4" /></Link></div></div></section>
      <section className="bg-[#f7f8fc] py-20 sm:py-28"><div className="mx-auto max-w-3xl px-6"><p className="text-sm font-semibold text-primary">Preguntas frecuentes</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em] text-[#171827]">Lo que normalmente preguntan antes de empezar.</h2><div className="mt-9 divide-y divide-[#dfe4ed] rounded-2xl border border-[#dfe4ed] bg-white px-5">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-[#34415a]">{question}<ChevronDown className="h-5 w-5 flex-none text-[#7b879a] transition-transform group-open:rotate-180" /></summary><p className="mt-3 max-w-2xl text-sm leading-7 text-[#687389]">{answer}</p></details>)}</div></div></section>
      <section className="bg-[#171827] py-20 text-white sm:py-24"><div className="mx-auto max-w-3xl px-6 text-center"><p className="text-sm font-semibold text-[#aeb8ff]">Tu carta es el punto de partida</p><h2 className="mt-4 text-balance text-4xl font-semibold leading-[1.05] tracking-[-0.045em] sm:text-5xl">Trae tu carta, te mostramos el margen de tus 10 platos más vendidos.</h2><p className="mt-5 text-lg leading-8 text-[#c6ccdd]">Conversemos sobre las fuentes que ya tienes y qué sería útil cruzar en tu operación.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/register" className="inline-flex items-center justify-center rounded-full bg-white px-5 py-3.5 text-sm font-semibold text-[#27304a]">Agendar una conversación <ArrowRight className="ml-2 h-4 w-4" /></Link><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-white/25 px-5 py-3.5 text-sm font-semibold text-white">Hablar por WhatsApp</a></div></div></section>
    </main><Footer />
  </div>;
}
