import { useState } from "react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, ChevronDown, Check } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { includedInEveryPlan, prepaidOptions, pricingPlans } from "@/content/pricing";

const faqs = [
  ["¿Qué pasa si supero el volumen de mi plan?", "Te avisamos antes de cualquier cambio. Revisamos el volumen real y acordamos contigo el plan o pricing que mejor calce. No cobramos excedentes ni cambiamos tu plan automáticamente."],
  ["¿Los precios incluyen IVA?", "Sí. Todos los precios publicados incluyen IVA."],
  ["¿Qué incluye mi plan?", "Todos los planes cubren el mismo tipo de trabajo. La diferencia es solamente el volumen mensual de facturas de compra que Ruka procesa."],
  ["¿Panel de Control y Stock están incluidos?", "Se activan sobre tu plan de Ruka. Su alcance se define según tu operación y te lo contamos antes de firmar."],
] as const;

export default function Precios() {
  const [selected, setSelected] = useState(0);
  const current = pricingPlans[selected];
  return <div className="min-h-screen bg-white text-[#171827]">
    <Helmet><title>Precios de Ruka | Facturas de compra por mes</title><meta name="description" content="Elige el plan de Ruka según la cantidad de facturas de compra que recibes al mes. Todos los precios incluyen IVA." /><link rel="canonical" href="https://www.ruka.ai/precios" /></Helmet>
    <Navbar />
    <main>
      <section className="bg-[#f7f8fc] pb-18 pt-28 sm:pb-24 sm:pt-36"><div className="mx-auto max-w-4xl px-6 text-center"><p className="text-sm font-semibold text-primary">Precios Ruka</p><h1 className="mx-auto mt-5 max-w-3xl text-balance text-5xl font-semibold leading-[0.98] tracking-[-0.055em] sm:text-7xl">Un precio, según cuántas facturas recibes al mes.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-[#586277]">Todos los planes hacen lo mismo. Lo único que cambia es el volumen que Ruka procesa cada mes. Todos los precios incluyen IVA.</p></div></section>
      <section className="py-16 sm:py-20"><div className="mx-auto max-w-6xl px-6"><div className="rounded-[28px] border border-[#dce2ef] bg-white p-6 shadow-[0_18px_50px_rgba(24,30,52,0.07)] sm:p-9"><div className="flex flex-col justify-between gap-4 border-b border-[#e7eaf1] pb-6 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-primary">Encuentra tu tramo</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em]">¿Cuántas facturas de compra recibes al mes?</h2></div><p className="max-w-sm text-sm leading-6 text-[#6b768b]">Si no lo tienes contado: multiplica tus proveedores habituales por las veces que te facturan al mes.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{pricingPlans.map((plan, index) => <button key={plan.name} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition-all ${selected === index ? "border-primary bg-[#f0f2ff] shadow-[0_8px_22px_rgba(80,101,233,0.12)]" : "border-[#dfe4ed] bg-white hover:border-[#bac4ef]"}`}><p className="text-sm font-semibold text-[#283650]">{plan.name}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{plan.price}</p><p className="mt-2 text-sm leading-6 text-[#667188]">{plan.capacity}</p></button>)}</div><div className="mt-7 rounded-xl bg-[#f7f8fc] px-5 py-4 text-sm text-[#536079]"><span className="font-semibold text-[#2d3a52]">Tu selección: </span>{current.name} · {current.capacity}</div></div></div></section>
      <section className="pb-20 sm:pb-28"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-4 lg:grid-cols-4">{pricingPlans.map((plan) => <article key={plan.name} className={`rounded-2xl border p-6 ${plan.featured ? "border-primary bg-[#f6f7ff] shadow-[0_16px_38px_rgba(80,101,233,0.12)]" : "border-[#dfe4ed] bg-white"}`}><p className="text-sm font-semibold text-primary">{plan.name}</p><p className="mt-5 text-4xl font-semibold tracking-[-0.05em]">{plan.price}</p><p className="mt-2 min-h-12 text-sm leading-6 text-[#657189]">{plan.capacity}</p><div className="mt-6 border-t border-[#dfe4ed] pt-5"><p className="text-sm font-semibold text-[#35415a]">Incluye</p>{includedInEveryPlan.map((item) => <p key={item} className="mt-3 flex gap-2 text-sm text-[#5b667c]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{item}</p>)}</div><Link to="/register" className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-[#171827] px-4 py-3 text-sm font-semibold text-white">{plan.name === "A medida" ? "Conversemos" : "Elegir este plan"}<ArrowRight className="ml-2 h-4 w-4" /></Link></article>)}</div></div></section>
      <section className="border-y border-[#e4e8f0] bg-[#f7f8fc] py-20"><div className="mx-auto grid max-w-6xl gap-10 px-6 lg:grid-cols-2"><div><p className="text-sm font-semibold text-primary">Productos complementarios</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em]">Panel de Control y Stock se activan sobre tu plan.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-[#5c677d]">El plan cubre el volumen de facturas que procesa Ruka. El alcance de cada producto se define según tu operación y te lo decimos antes de que firmes, no después.</p><div className="mt-7 flex gap-3"><Link to="/productos/panel-control" className="text-sm font-semibold text-primary">Ver Panel de Control →</Link><Link to="/productos/stock" className="text-sm font-semibold text-primary">Ver Stock →</Link></div></div><div className="rounded-2xl border border-[#d8def0] bg-white p-7"><p className="text-sm font-semibold text-primary">Pago anticipado</p><h3 className="mt-3 text-2xl font-semibold tracking-[-0.035em]">Ahorra al comprometer un período.</h3><div className="mt-6 grid grid-cols-3 gap-3">{prepaidOptions.map((option) => <div key={option.term} className="rounded-xl bg-[#f5f7fc] p-3 text-center"><p className="text-sm font-semibold text-[#29364e]">{option.term}</p><p className="mt-1 text-lg font-semibold text-primary">{option.discount}</p></div>)}</div><p className="mt-6 text-sm leading-6 text-[#667188]">El descuento aplica al plan contratado, se paga en una sola cuota al inicio y mantiene el precio acordado durante su vigencia. Si necesitas cambiar de tramo, lo conversamos antes de ajustar el valor.</p></div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-3xl px-6"><p className="text-sm font-semibold text-primary">Preguntas frecuentes</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.045em]">Sin letras chicas.</h2><div className="mt-9 divide-y divide-[#dfe4ed] border-y border-[#dfe4ed]">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-[#34415a]">{question}<ChevronDown className="h-5 w-5 text-[#7a8497] transition-transform group-open:rotate-180" /></summary><p className="mt-3 text-sm leading-7 text-[#667188]">{answer}</p></details>)}</div></div></section>
      <section className="bg-[#171827] py-20 text-white"><div className="mx-auto max-w-3xl px-6 text-center"><BadgeCheck className="mx-auto h-6 w-6 text-[#aeb8ff]" /><h2 className="mt-4 text-balance text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">¿No sabes cuántas facturas recibes?</h2><p className="mt-5 text-lg leading-8 text-[#c6ccdd]">Cuéntanos cómo opera hoy tu equipo y te ayudamos a elegir el tramo correcto.</p><Link to="/register" className="mt-8 inline-flex items-center rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#28324a]">Hablar con Ruka <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section>
    </main>
    <Footer />
  </div>;
}
