import type { ProductPageContent } from "@/components/seo/ProductLandingPage";

export const productPages = {
  registro: {
    path: "/productos/registro-de-compras",
    name: "Registro de compras",
    title: "Automatiza el registro de compras | Ruka",
    description: "Ruka recibe facturas desde SII, XML, PDF y correo, aplica tus reglas y deja cada compra registrada en los sistemas que tu empresa ya usa.",
    h1: "Las compras llegan. Ruka hace el registro.",
    lead: "Reúne facturas, valida la información y deja cada compra donde corresponde. Sin perseguir documentos ni volver a ingresar los mismos datos.",
    promise: "La información llega por los mismos canales. Lo que desaparece es el trabajo manual entre medio.",
    outcomes: [
      { title: "Una sola entrada", description: "SII, XML, PDF, correo y documentos físicos." },
      { title: "Tus reglas aplicadas", description: "Lectura, homologación y validación consistentes." },
      { title: "Registro terminado", description: "La compra queda actualizada donde la necesitas." },
    ],
    flowTitle: "De documento recibido a compra registrada.",
    flowLead: "Ruka sigue un flujo claro y deja trazabilidad de cada paso.",
    flow: [
      { number: "01", title: "Recibe", description: "Reúne la información que hoy llega por distintos canales y la asocia al proceso correcto." },
      { number: "02", title: "Lee y valida", description: "Extrae los datos, aplica homologaciones y comprueba las reglas que define tu operación." },
      { number: "03", title: "Registra", description: "Actualiza el ERP, POS, planilla o sistema contable que tu equipo ya utiliza." },
    ],
    faqs: [
      { question: "¿Con qué documentos puede trabajar Ruka?", answer: "Ruka puede trabajar con información de SII, XML, PDF, correo, planillas y otras fuentes disponibles para el proceso." },
      { question: "¿Tengo que cambiar mi ERP o sistema contable?", answer: "No. Ruka trabaja sobre las herramientas que ya usa tu empresa y deja la información actualizada donde corresponde." },
      { question: "¿Qué pasa si un documento no cumple una regla?", answer: "El flujo separa los casos que necesitan una decisión para que tu equipo no tenga que revisar todo el volumen." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Ruka conecta los sistemas de una empresa y ejecuta trabajo operativo",
  },
  conciliacion: {
    path: "/productos/conciliacion-automatica",
    name: "Conciliación automática",
    title: "Conciliación automática de facturas, órdenes y pagos | Ruka",
    description: "Ruka cruza facturas, órdenes de compra, recepciones y pagos según las reglas de tu equipo, y separa las diferencias que necesitan revisión.",
    h1: "Ruka concilia el volumen. Tu equipo decide las diferencias.",
    lead: "Cruza cada factura con su orden, su recepción y su pago. Lo que calza avanza; lo que no, queda explicado y listo para decidir.",
    promise: "Tu equipo deja de buscar diferencias. Recibe directamente los casos que necesitan una decisión.",
    outcomes: [
      { title: "Cada caso completo", description: "Factura, orden, recepción y pago en un mismo lugar." },
      { title: "Criterios consistentes", description: "Las reglas y tolerancias de tu operación se aplican siempre igual." },
      { title: "Diferencias explicadas", description: "Esperado, recibido y documento de origen visibles." },
    ],
    flowTitle: "Cuatro fuentes. Una conciliación trazable.",
    flowLead: "Cada resultado conserva el camino de vuelta a los documentos que lo explican.",
    flow: [
      { number: "01", title: "Arma el caso", description: "Asocia la factura, la orden de compra, la recepción y el movimiento bancario." },
      { number: "02", title: "Aplica tus reglas", description: "Compara monto, proveedor, fecha, cantidades y tolerancias definidas por tu equipo." },
      { number: "03", title: "Separa lo importante", description: "Los casos correctos avanzan y las diferencias quedan listas para revisar." },
    ],
    faqs: [
      { question: "¿Qué pasa con las facturas que sí calzan?", answer: "Avanzan sin revisión manual y queda registrado qué reglas permitieron validarlas." },
      { question: "¿Qué información cruza Ruka?", answer: "Puede cruzar facturas, órdenes de compra, recepciones y pagos. El alcance depende de las fuentes disponibles." },
      { question: "¿Puede trabajar con información bancaria?", answer: "Sí, cuando el proceso cuenta con acceso a las cartolas o movimientos necesarios." },
      { question: "¿Qué ocurre con una diferencia aceptable?", answer: "Tu equipo puede definirla como tolerancia para que deje de aparecer como excepción." },
    ],
  },
  cuentas: {
    path: "/productos/cuentas-por-pagar",
    name: "Cuentas por pagar",
    title: "Automatiza cuentas por pagar y pagos a proveedores | Ruka",
    description: "Ruka ordena facturas, vincula cada recepción y genera la nómina masiva en el formato del banco, lista para subir y pagar.",
    h1: "Tus cuentas por pagar, listas para ejecutar.",
    lead: "Ruka reúne las facturas, confirma qué se recibió y prepara la información que necesita tu equipo antes de pagar a proveedores.",
    promise: "De las facturas aprobadas a una nómina bancaria lista para subir.",
    outcomes: [
      { title: "Nómina en un clic", description: "Archivo masivo listo para cargar en tu banco." },
      { title: "Recepciones vinculadas", description: "Lo recibido y sus diferencias asociados a cada factura." },
      { title: "Control antes de pagar", description: "Los documentos con observaciones no avanzan por error." },
    ],
    flowTitle: "De la factura aprobada a la nómina bancaria.",
    flowLead: "El flujo confirma lo que llegó y genera el archivo masivo que tu banco necesita.",
    flow: [
      { number: "01", title: "Ordena las obligaciones", description: "Centraliza facturas, fechas y proveedores para que el equipo vea qué viene." },
      { number: "02", title: "Confirma la recepción", description: "Relaciona cantidades recibidas, faltantes y evidencia con la factura que no debería avanzar todavía." },
      { number: "03", title: "Genera la nómina", description: "Crea en un clic el archivo masivo en el formato requerido por tu banco, listo para subir." },
    ],
    faqs: [
      { question: "¿Ruka ejecuta los pagos por sí sola?", answer: "No. Ruka genera la nómina masiva en el formato de tu banco. Tu equipo la descarga, la sube y conserva el control final del pago." },
      { question: "¿Qué pasa con una factura observada?", answer: "Queda vinculada a su incidencia para que no avance como si estuviera correcta." },
      { question: "¿Cómo se considera la recepción antes de pagar?", answer: "Ruka vincula la factura con lo efectivamente recibido. Si hay un faltante o una diferencia, el caso queda visible antes de preparar el pago." },
      { question: "¿Puedo mantener mi banco y sistema contable?", answer: "Sí. El flujo se diseña sobre las herramientas y formatos que tu operación ya utiliza." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Flujo de cuentas por pagar operado por Ruka",
  },
  panel: {
    path: "/productos/panel-control",
    name: "Panel de control",
    title: "Panel de control de costos y margen | Ruka",
    description: "Ruka cruza ventas, compras y recetas para mantener costos y márgenes operativos disponibles en un solo lugar.",
    h1: "El margen cambia. Tu visión también debería.",
    lead: "Cruza ventas, compras y costos reales para entender qué está pasando en tu operación sin reconstruir el dato en una planilla.",
    promise: "No es otro dashboard para alimentar. Es información operativa que Ruka mantiene al día.",
    outcomes: [
      { title: "Costo actualizado", description: "Cambios de compra reflejados en tus productos y recetas." },
      { title: "Margen visible", description: "Ventas y costos reunidos en una lectura accionable." },
      { title: "Desvíos detectables", description: "Variaciones relevantes visibles antes de fin de mes." },
    ],
    flowTitle: "De datos separados a una decisión operativa.",
    flowLead: "Ruka mantiene la conexión entre lo que compras, lo que vendes y lo que realmente te deja margen.",
    flow: [
      { number: "01", title: "Conecta ventas y compras", description: "Reúne la información del POS, las facturas y las fuentes que explican tu costo." },
      { number: "02", title: "Actualiza la relación", description: "Propaga los cambios relevantes a productos, recetas y categorías." },
      { number: "03", title: "Muestra el impacto", description: "Deja visibles costos, margen y variaciones donde tu equipo puede actuar." },
    ],
    faqs: [
      { question: "¿Tengo que cargar los costos manualmente?", answer: "El objetivo es conectarlos desde las fuentes disponibles y reducir la actualización manual al mínimo." },
      { question: "¿Funciona con cualquier POS?", answer: "Depende del acceso disponible. Revisamos la integración y el alcance antes de implementar el flujo." },
      { question: "¿Reemplaza mi herramienta de reportería?", answer: "No necesariamente. Puede alimentar o complementar las herramientas que tu equipo ya utiliza." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Panel de costos y margen de Ruka",
  },
  stock: {
    path: "/productos/stock",
    name: "Stock",
    title: "Gestión de stock e inventario conectada | Ruka",
    description: "Ruka registra compras, movimientos y traspasos para mantener el inventario actualizado entre bodegas y sistemas.",
    h1: "El stock se actualiza mientras la operación ocurre.",
    lead: "Convierte compras confirmadas, recepciones y traspasos en movimientos trazables. Sin mantener el inventario a punta de planillas.",
    promise: "El inventario deja de ser una reconstrucción tardía y pasa a reflejar el trabajo que ya ocurrió.",
    outcomes: [
      { title: "Ingresos automáticos", description: "Compras confirmadas convertidas en movimientos de stock." },
      { title: "Bodegas conectadas", description: "Traspasos y recepciones con responsables y trazabilidad." },
      { title: "Diferencias visibles", description: "Inventarios y faltantes concentrados donde hace falta revisar." },
    ],
    flowTitle: "Cada movimiento deja el inventario al día.",
    flowLead: "La información se actualiza a partir de eventos concretos de la operación.",
    flow: [
      { number: "01", title: "Registra el ingreso", description: "Una compra o recepción confirmada actualiza el stock de la bodega correspondiente." },
      { number: "02", title: "Controla el movimiento", description: "Solicitudes, aprobaciones y traspasos quedan asociados a usuarios y ubicaciones." },
      { number: "03", title: "Contrasta el inventario", description: "Los conteos periódicos muestran diferencias y permiten corregirlas con trazabilidad." },
    ],
    faqs: [
      { question: "¿Puede trabajar con varias bodegas?", answer: "Sí. El flujo puede distinguir ubicaciones, responsables y movimientos entre bodegas." },
      { question: "¿Cómo se registran los ingresos?", answer: "Pueden originarse desde compras o recepciones confirmadas, según las reglas del proceso." },
      { question: "¿Tengo que reemplazar mi sistema de inventario?", answer: "No. Ruka puede actualizar el sistema existente cuando existe acceso suficiente para hacerlo." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Ruka conecta los sistemas de una empresa y ejecuta trabajo operativo",
  },
} satisfies Record<string, ProductPageContent>;
