import type { ProductPageContent } from "@/components/seo/ProductLandingPage";

export const productPages = {
  registro: {
    path: "/productos/registro-de-compras",
    name: "Registro de compras",
    title: "Registro de compras automático para empresas | Ruka",
    description: "Automatiza el registro de compras desde SII, XML, PDF y correo. Ruka lee cada factura y la ingresa en el ERP, POS o sistema contable que ya usas.",
    h1: "Tus facturas llegan. Ruka las registra.",
    lead: "Ruka reúne las facturas que llegan por SII, correo, XML o PDF, lee sus datos y las ingresa en el sistema que ya usa tu empresa.",
    promise: "La factura es la misma. Lo que desaparece es volver a leerla y copiarla a mano.",
    outcomes: [
      { title: "Todo en una bandeja", description: "SII, XML, PDF, correo y documentos físicos." },
      { title: "Datos listos", description: "Proveedor, folio, montos e ítems leídos y validados." },
      { title: "Compra registrada", description: "En tu ERP, POS, planilla o sistema contable." },
    ],
    flowTitle: "Así se automatiza el registro de compras.",
    flowLead: "Ruka toma el documento desde que llega y lo deja registrado sin pedirle a tu equipo que repita el trabajo.",
    flow: [
      { number: "01", title: "Reúne las facturas", description: "Trae los documentos desde SII, correo, XML, PDF u otras fuentes que ya recibe tu empresa." },
      { number: "02", title: "Lee y ordena los datos", description: "Identifica proveedor, folio, fechas, montos e ítems, y homologa la información que viene escrita de distintas formas." },
      { number: "03", title: "Hace el registro", description: "Ingresa la compra en el ERP, POS, planilla o sistema contable que tu equipo ya utiliza." },
    ],
    faqs: [
      { question: "¿Desde dónde puede tomar las facturas?", answer: "Ruka puede recibir información desde SII, XML, PDF, correo, planillas y documentos físicos digitalizados. Las fuentes exactas se definen según tu proceso." },
      { question: "¿Tengo que cambiar mi ERP o sistema contable?", answer: "No. Ruka registra la compra en las herramientas que tu empresa ya usa, siempre que exista una forma segura de conectarlas." },
      { question: "¿Qué pasa si una factura viene incompleta o con un dato extraño?", answer: "Ruka separa ese documento y muestra qué necesita revisión. Tu equipo se ocupa del caso puntual, no de leer todas las facturas." },
      { question: "¿Esto reemplaza el Registro de Compras y Ventas del SII?", answer: "No. Ruka puede usar la información disponible en el SII y llevarla a tu proceso interno; no reemplaza las obligaciones tributarias de tu empresa." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Registro automático de facturas de compra con Ruka",
  },
  conciliacion: {
    path: "/productos/conciliacion-automatica",
    name: "Conciliación automática",
    title: "Conciliación automática de facturas y órdenes | Ruka",
    description: "Ruka concilia facturas con órdenes de compra, recepciones y pagos. Lo que coincide avanza; las diferencias quedan explicadas para que puedas resolverlas.",
    h1: "Factura, orden y recepción. Ruka revisa que todo calce.",
    lead: "Ruka junta los documentos de cada compra y los compara uno a uno. Si coinciden, el caso avanza; si hay una diferencia, te muestra exactamente cuál es.",
    promise: "Tu equipo deja de revisar cada compra y se concentra solo en las diferencias reales.",
    outcomes: [
      { title: "Documentos conectados", description: "Factura, orden, recepción y pago en un mismo caso." },
      { title: "Cruce automático", description: "Monto, proveedor, fecha, cantidades y tolerancias." },
      { title: "Diferencia clara", description: "Qué se esperaba, qué llegó y dónde está el problema." },
    ],
    flowTitle: "Así funciona la conciliación automática.",
    flowLead: "Cada resultado queda conectado a los documentos que lo explican, para que puedas comprobarlo sin volver a buscar todo desde cero.",
    flow: [
      { number: "01", title: "Junta cada compra", description: "Relaciona la factura con su orden de compra, la recepción y el pago cuando esa información está disponible." },
      { number: "02", title: "Comprueba que coincidan", description: "Compara proveedor, monto, fecha, cantidades y las tolerancias que ya utiliza tu equipo." },
      { number: "03", title: "Deja solo lo que hay que resolver", description: "Los casos correctos avanzan. Las diferencias muestran su origen y quedan listas para decidir." },
    ],
    faqs: [
      { question: "¿Qué pasa con las facturas que sí coinciden?", answer: "Avanzan sin que una persona tenga que revisarlas una por una. Ruka conserva el resultado y los documentos usados para validarlo." },
      { question: "¿Qué documentos puede conciliar Ruka?", answer: "Puede cruzar facturas, órdenes de compra, recepciones y pagos. El alcance exacto depende de la información a la que podamos acceder." },
      { question: "¿Esto también sirve para conciliación bancaria?", answer: "Puede incluir movimientos bancarios cuando forman parte del proceso y existe acceso a esa información. La página se enfoca en conciliar cada compra de punta a punta." },
      { question: "¿Qué pasa con una diferencia pequeña que mi empresa acepta?", answer: "Puedes definir tolerancias para que Ruka reconozca esos casos como válidos y no los envíe a revisión." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Conciliación automática de facturas, órdenes de compra y recepciones con Ruka",
  },
  cuentas: {
    path: "/productos/cuentas-por-pagar",
    name: "Cuentas por pagar",
    title: "Automatiza cuentas por pagar y pagos a proveedores | Ruka",
    description: "Automatiza tus cuentas por pagar: Ruka ordena facturas, confirma recepciones y genera la nómina masiva en el formato de tu banco, lista para subir.",
    h1: "Deja el pago a proveedores listo para el banco.",
    lead: "Ruka reúne las facturas aprobadas, confirma qué se recibió y genera la nómina masiva que tu equipo sube al banco para pagar.",
    promise: "Selecciona las facturas aprobadas y descarga la nómina. Ruka deja el pago masivo listo para el banco.",
    outcomes: [
      { title: "Nómina en un clic", description: "El archivo masivo en el formato que pide tu banco." },
      { title: "Recepción confirmada", description: "Cada factura muestra qué llegó y si hubo diferencias." },
      { title: "Pago bajo control", description: "Las facturas observadas no entran por error en la nómina." },
    ],
    flowTitle: "Así preparas el pago masivo a proveedores.",
    flowLead: "Ruka ordena lo pendiente, comprueba qué se puede pagar y arma el archivo que después subes al banco.",
    flow: [
      { number: "01", title: "Ordena lo que hay que pagar", description: "Reúne facturas, fechas de vencimiento y proveedores para que el equipo vea todo lo pendiente." },
      { number: "02", title: "Comprueba qué puede avanzar", description: "Vincula cada factura con la recepción y deja fuera las que tienen faltantes o diferencias pendientes." },
      { number: "03", title: "Genera la nómina bancaria", description: "Crea en un clic el archivo masivo en el formato requerido por tu banco, listo para subir." },
    ],
    faqs: [
      { question: "¿Ruka paga directamente desde mi cuenta bancaria?", answer: "No. Ruka genera la nómina masiva en el formato de tu banco. Tu equipo la descarga, la sube y conserva el control final del pago." },
      { question: "¿Qué pasa con una factura que tiene una diferencia?", answer: "Queda vinculada a su observación y no entra en la nómina como si estuviera aprobada." },
      { question: "¿Cómo comprueba Ruka que la mercadería llegó?", answer: "Relaciona la factura con la recepción registrada por tu equipo. Si falta algo o existe una incidencia, queda visible antes de preparar el pago." },
      { question: "¿Tengo que cambiar de banco o sistema contable?", answer: "No. Adaptamos la salida al formato de tu banco y trabajamos con los sistemas que ya utiliza tu empresa, siempre que podamos conectarlos de forma segura." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Cuentas por pagar y nómina bancaria para proveedores en Ruka",
  },
  panel: {
    path: "/productos/panel-control",
    name: "Control de costos y margen",
    title: "Control de costos y margen operativo | Ruka",
    description: "Controla costos y margen con ventas, compras y recetas conectadas. Ruka actualiza la información para que veas qué productos ganan o pierden rentabilidad.",
    h1: "Ve cuánto te deja cada producto, sin rehacer planillas.",
    lead: "Ruka conecta lo que vendes con lo que compras y mantiene los costos actualizados para que puedas ver el margen de cada producto y local.",
    promise: "Cuando cambia un costo, puedes ver dónde pega. Sin esperar al cierre de mes ni reconstruir el dato a mano.",
    outcomes: [
      { title: "Costos al día", description: "Los cambios de compra se reflejan en productos y recetas." },
      { title: "Margen por producto", description: "Ventas y costos reunidos en una sola lectura." },
      { title: "Cambios a tiempo", description: "Detecta una variación antes de llegar al cierre de mes." },
    ],
    flowTitle: "Así se mantiene actualizado tu margen.",
    flowLead: "Ruka conecta ventas, compras y recetas para que el cálculo siga a la operación, no a una planilla que alguien actualiza después.",
    flow: [
      { number: "01", title: "Trae ventas y compras", description: "Reúne la información del POS, las facturas y otras fuentes que explican cuánto cuesta lo que vendes." },
      { number: "02", title: "Actualiza productos y recetas", description: "Lleva cada cambio de costo a los productos, recetas y categorías que dependen de ese insumo." },
      { number: "03", title: "Muestra qué cambió", description: "Deja visibles el costo, el margen y la variación para que el equipo sepa dónde actuar." },
    ],
    faqs: [
      { question: "¿Tengo que actualizar los costos manualmente?", answer: "La idea es traerlos desde las fuentes disponibles y reflejar sus cambios sin que una persona tenga que mantener otra planilla." },
      { question: "¿Puedo ver el margen por producto o por local?", answer: "Sí, cuando las ventas, compras y relaciones necesarias están disponibles. Definimos el nivel de detalle al revisar tu operación." },
      { question: "¿Funciona con cualquier POS?", answer: "Depende del acceso que entregue cada sistema. Antes de implementar revisamos la integración y qué información podemos obtener." },
      { question: "¿Reemplaza mi herramienta de reportería?", answer: "No necesariamente. Ruka puede alimentar o complementar las herramientas que tu equipo ya usa." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Control de costos y margen por producto en Ruka",
  },
  stock: {
    path: "/productos/stock",
    name: "Control de stock e inventario",
    title: "Software para control de stock e inventario | Ruka",
    description: "Controla stock e inventario con compras, recepciones y traspasos conectados. Ruka registra cada movimiento y mantiene tus bodegas actualizadas.",
    h1: "Cada movimiento actualiza tu stock.",
    lead: "Cuando recibes una compra, mueves mercadería o haces un conteo, Ruka registra el cambio y mantiene actualizado el inventario de cada bodega.",
    promise: "El inventario se actualiza cuando ocurre el movimiento, no cuando alguien encuentra tiempo para cuadrar la planilla.",
    outcomes: [
      { title: "Ingresos registrados", description: "Cada recepción confirmada suma stock en su bodega." },
      { title: "Traspasos trazables", description: "Origen, destino, responsable y estado del movimiento." },
      { title: "Diferencias visibles", description: "El conteo muestra qué falta y dónde hay que revisar." },
    ],
    flowTitle: "Así se mantiene actualizado el inventario.",
    flowLead: "Ruka convierte cada recepción, traspaso y conteo en un movimiento que el equipo puede seguir hasta su origen.",
    flow: [
      { number: "01", title: "Suma lo que recibes", description: "Una compra o recepción confirmada actualiza el stock de la bodega que corresponde." },
      { number: "02", title: "Sigue cada traspaso", description: "La solicitud, la aprobación y el movimiento quedan asociados a sus responsables y ubicaciones." },
      { number: "03", title: "Compara contra el conteo", description: "Los inventarios físicos muestran las diferencias y permiten corregirlas sin perder el historial." },
    ],
    faqs: [
      { question: "¿Puedo controlar stock en varias bodegas?", answer: "Sí. Ruka puede distinguir ubicaciones, responsables y movimientos entre bodegas." },
      { question: "¿Cómo se registran los ingresos de inventario?", answer: "Pueden nacer desde una compra o una recepción confirmada. Definimos el momento exacto según cómo trabaja tu equipo." },
      { question: "¿Qué pasa si el conteo físico no coincide?", answer: "La diferencia queda visible para revisarla y, si corresponde, hacer un ajuste con su historial y responsable." },
      { question: "¿Tengo que reemplazar mi sistema de inventario?", answer: "No necesariamente. Ruka puede actualizar el sistema existente cuando contamos con acceso suficiente para conectarlo." },
    ],
    image: "/ruka-agentes-ia-operaciones-og.png",
    imageAlt: "Control de stock e inventario entre bodegas con Ruka",
  },
} satisfies Record<string, ProductPageContent>;
