create table if not exists public.leads_one (
  id bigint generated by default as identity primary key,
  submission_id uuid not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  company text not null,
  email text not null,
  whatsapp text not null,
  landing_path text not null default '/one/contacto',
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  status text not null default 'submitted'
    check (status in ('submitted', 'calendly_scheduled')),
  calendly_event_uri text,
  calendly_scheduled_at timestamptz,
  slack_thread_ts text,
  slack_notified_at timestamptz,
  calendly_slack_notified_at timestamptz,
  constraint leads_one_name_length check (char_length(name) between 2 and 120),
  constraint leads_one_company_length check (char_length(company) between 2 and 160),
  constraint leads_one_email_length check (char_length(email) between 3 and 254),
  constraint leads_one_whatsapp_length check (char_length(whatsapp) between 8 and 32)
);

create index if not exists leads_one_created_at_idx
  on public.leads_one (created_at desc);

create index if not exists leads_one_status_idx
  on public.leads_one (status, created_at desc);

create index if not exists leads_one_email_idx
  on public.leads_one (lower(email));

alter table public.leads_one enable row level security;

revoke all on table public.leads_one from anon, authenticated;
revoke all on sequence public.leads_one_id_seq from anon, authenticated;
grant all on table public.leads_one to service_role;
grant usage, select on sequence public.leads_one_id_seq to service_role;

comment on table public.leads_one is
  'Leads captured by the isolated Ruka One contact flow.';
comment on column public.leads_one.submission_id is
  'Browser-generated idempotency key shared by form, Slack and Calendly events.';
