create extension if not exists pgcrypto;

create table if not exists public.organic_growth_state (
  engine_key text primary key default 'ruka',
  timezone text not null default 'America/Santiago',
  next_execution_at timestamptz not null default now(),
  next_report_at timestamptz not null default now(),
  execution_lease_run_id uuid,
  execution_lease_expires_at timestamptz,
  reporting_lease_run_id uuid,
  reporting_lease_expires_at timestamptz,
  last_execution_success_at timestamptz,
  last_report_success_at timestamptz,
  last_data_through_date date,
  updated_at timestamptz not null default now(),
  constraint organic_growth_state_engine_key check (engine_key = 'ruka')
);

create table if not exists public.organic_growth_runs (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('execution', 'reporting')),
  trigger_source text not null default 'schedule',
  status text not null default 'running'
    check (status in ('running', 'succeeded', 'failed', 'skipped')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  data_through_date date,
  git_sha text,
  pull_request_url text,
  deployment_url text,
  summary jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists organic_growth_runs_kind_started_idx
  on public.organic_growth_runs (kind, started_at desc);

create table if not exists public.organic_growth_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid references public.organic_growth_runs(id) on delete set null,
  data_through_date date not null,
  captured_at timestamptz not null default now(),
  property text not null default 'sc-domain:ruka.ai',
  payload jsonb not null,
  unique (run_id, data_through_date)
);

create index if not exists organic_growth_snapshots_date_idx
  on public.organic_growth_snapshots (data_through_date desc);

create table if not exists public.organic_growth_opportunities (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null unique,
  title text not null,
  cluster text not null,
  target_url text,
  intent text not null check (intent in ('commercial', 'informational', 'branded', 'technical')),
  evidence jsonb not null default '[]'::jsonb,
  commercial_intent smallint not null check (commercial_intent between 0 and 5),
  demand_confidence smallint not null check (demand_confidence between 0 and 5),
  ruka_advantage smallint not null check (ruka_advantage between 0 and 5),
  effort smallint not null check (effort between 1 and 5),
  risk smallint not null check (risk between 0 and 5),
  priority_score numeric(8,2) generated always as
    (((commercial_intent * 2.0) + demand_confidence + ruka_advantage - risk) / effort) stored,
  status text not null default 'discovered'
    check (status in ('discovered', 'prioritized', 'in_progress', 'deployed', 'measuring', 'validated', 'inconclusive', 'reverted', 'approval_required', 'discarded')),
  approval_reason text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists organic_growth_opportunities_priority_idx
  on public.organic_growth_opportunities (status, priority_score desc);

create table if not exists public.organic_growth_experiments (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid references public.organic_growth_opportunities(id) on delete set null,
  run_id uuid references public.organic_growth_runs(id) on delete set null,
  title text not null,
  status text not null default 'discovered'
    check (status in ('discovered', 'prioritized', 'in_progress', 'deployed', 'measuring', 'validated', 'inconclusive', 'reverted')),
  affected_urls text[] not null default '{}',
  hypothesis text not null,
  evidence jsonb not null default '[]'::jsonb,
  baseline jsonb not null default '{}'::jsonb,
  success_metrics jsonb not null default '{}'::jsonb,
  exact_changes text,
  target_cluster text,
  detected_at timestamptz not null default now(),
  implemented_at timestamptz,
  deployed_at timestamptz,
  evaluate_after timestamptz,
  git_sha text,
  deployment_url text,
  indexation_status jsonb not null default '{}'::jsonb,
  results jsonb not null default '{}'::jsonb,
  conclusion text,
  updated_at timestamptz not null default now()
);

create index if not exists organic_growth_experiments_status_idx
  on public.organic_growth_experiments (status, evaluate_after);

create table if not exists public.organic_growth_product_signals (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null unique,
  repository text not null,
  source_ref text not null,
  observed_at timestamptz not null default now(),
  capability text not null,
  maturity text not null check (maturity in ('active', 'partial', 'experimental', 'future', 'unknown')),
  public_safe_summary text not null,
  commercial_problem text,
  supporting_evidence jsonb not null default '[]'::jsonb,
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.organic_growth_reports (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.organic_growth_runs(id) on delete set null,
  period_end date not null,
  payload jsonb not null,
  slack_channel_id text,
  slack_timestamp text,
  delivery_status text not null default 'pending'
    check (delivery_status in ('pending', 'sent', 'failed')),
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

alter table public.organic_growth_state enable row level security;
alter table public.organic_growth_runs enable row level security;
alter table public.organic_growth_snapshots enable row level security;
alter table public.organic_growth_opportunities enable row level security;
alter table public.organic_growth_experiments enable row level security;
alter table public.organic_growth_product_signals enable row level security;
alter table public.organic_growth_reports enable row level security;

revoke all on public.organic_growth_state from anon, authenticated;
revoke all on public.organic_growth_runs from anon, authenticated;
revoke all on public.organic_growth_snapshots from anon, authenticated;
revoke all on public.organic_growth_opportunities from anon, authenticated;
revoke all on public.organic_growth_experiments from anon, authenticated;
revoke all on public.organic_growth_product_signals from anon, authenticated;
revoke all on public.organic_growth_reports from anon, authenticated;

grant all on public.organic_growth_state to service_role;
grant all on public.organic_growth_runs to service_role;
grant all on public.organic_growth_snapshots to service_role;
grant all on public.organic_growth_opportunities to service_role;
grant all on public.organic_growth_experiments to service_role;
grant all on public.organic_growth_product_signals to service_role;
grant all on public.organic_growth_reports to service_role;
grant usage, select on sequence public.organic_growth_snapshots_id_seq to service_role;

create or replace function public.organic_growth_next_report_at(p_after timestamptz)
returns timestamptz
language plpgsql
immutable
as $$
declare
  local_after timestamp := p_after at time zone 'America/Santiago';
  candidate date;
begin
  if extract(day from local_after)::int < 15 then
    candidate := make_date(extract(year from local_after)::int, extract(month from local_after)::int, 15);
  else
    candidate := (date_trunc('month', local_after) + interval '1 month')::date;
  end if;
  return (candidate + time '09:00') at time zone 'America/Santiago';
end;
$$;

insert into public.organic_growth_state (engine_key, next_execution_at, next_report_at)
values ('ruka', now(), public.organic_growth_next_report_at(now()))
on conflict (engine_key) do nothing;

create or replace function public.claim_organic_growth_job(
  p_kind text,
  p_trigger_source text default 'schedule',
  p_force boolean default false
)
returns table (claimed boolean, run_id uuid, reason text, next_due_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  state_row public.organic_growth_state%rowtype;
  new_run_id uuid;
  due_at timestamptz;
begin
  if p_kind not in ('execution', 'reporting') then
    raise exception 'Invalid organic growth job kind: %', p_kind;
  end if;

  select * into state_row
  from public.organic_growth_state
  where engine_key = 'ruka'
  for update;

  if (p_kind = 'execution' and state_row.execution_lease_run_id is not null and state_row.execution_lease_expires_at > now())
     or (p_kind = 'reporting' and state_row.reporting_lease_run_id is not null and state_row.reporting_lease_expires_at > now()) then
    return query select false, null::uuid, 'active_lease',
      case when p_kind = 'execution' then state_row.next_execution_at else state_row.next_report_at end;
    return;
  end if;

  due_at := case when p_kind = 'execution' then state_row.next_execution_at else state_row.next_report_at end;
  if not p_force and due_at > now() then
    return query select false, null::uuid, 'not_due', due_at;
    return;
  end if;

  insert into public.organic_growth_runs (kind, trigger_source)
  values (p_kind, left(coalesce(p_trigger_source, 'schedule'), 80))
  returning id into new_run_id;

  update public.organic_growth_state
  set execution_lease_run_id = case when p_kind = 'execution' then new_run_id else execution_lease_run_id end,
      execution_lease_expires_at = case when p_kind = 'execution' then now() + interval '2 hours' else execution_lease_expires_at end,
      reporting_lease_run_id = case when p_kind = 'reporting' then new_run_id else reporting_lease_run_id end,
      reporting_lease_expires_at = case when p_kind = 'reporting' then now() + interval '2 hours' else reporting_lease_expires_at end,
      updated_at = now()
  where engine_key = 'ruka';

  return query select true, new_run_id, 'claimed', due_at;
end;
$$;

create or replace function public.finish_organic_growth_job(
  p_run_id uuid,
  p_success boolean,
  p_summary jsonb default '{}'::jsonb,
  p_error_message text default null,
  p_data_through_date date default null,
  p_git_sha text default null,
  p_pull_request_url text default null,
  p_deployment_url text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  run_kind text;
begin
  select kind into run_kind from public.organic_growth_runs where id = p_run_id for update;
  if run_kind is null then raise exception 'Unknown run %', p_run_id; end if;

  update public.organic_growth_runs
  set status = case when p_success then 'succeeded' else 'failed' end,
      finished_at = now(),
      data_through_date = coalesce(p_data_through_date, data_through_date),
      git_sha = coalesce(p_git_sha, git_sha),
      pull_request_url = coalesce(p_pull_request_url, pull_request_url),
      deployment_url = coalesce(p_deployment_url, deployment_url),
      summary = coalesce(p_summary, '{}'::jsonb),
      error_message = case when p_success then null else left(coalesce(p_error_message, 'Unknown failure'), 8000) end
  where id = p_run_id;

  update public.organic_growth_state
  set next_execution_at = case
        when run_kind = 'execution' and p_success then now() + interval '5 days'
        when run_kind = 'execution' then now() + interval '6 hours'
        else next_execution_at end,
      next_report_at = case
        when run_kind = 'reporting' and p_success then public.organic_growth_next_report_at(now())
        when run_kind = 'reporting' then now() + interval '2 hours'
        else next_report_at end,
      last_execution_success_at = case when run_kind = 'execution' and p_success then now() else last_execution_success_at end,
      last_report_success_at = case when run_kind = 'reporting' and p_success then now() else last_report_success_at end,
      last_data_through_date = coalesce(p_data_through_date, last_data_through_date),
      execution_lease_run_id = case when run_kind = 'execution' and execution_lease_run_id = p_run_id then null else execution_lease_run_id end,
      execution_lease_expires_at = case when run_kind = 'execution' and execution_lease_run_id = p_run_id then null else execution_lease_expires_at end,
      reporting_lease_run_id = case when run_kind = 'reporting' and reporting_lease_run_id = p_run_id then null else reporting_lease_run_id end,
      reporting_lease_expires_at = case when run_kind = 'reporting' and reporting_lease_run_id = p_run_id then null else reporting_lease_expires_at end,
      updated_at = now()
  where engine_key = 'ruka'
    and ((run_kind = 'execution' and execution_lease_run_id = p_run_id)
      or (run_kind = 'reporting' and reporting_lease_run_id = p_run_id));

  return true;
end;
$$;

revoke all on function public.claim_organic_growth_job(text, text, boolean) from public, anon, authenticated;
revoke all on function public.finish_organic_growth_job(uuid, boolean, jsonb, text, date, text, text, text) from public, anon, authenticated;
grant execute on function public.claim_organic_growth_job(text, text, boolean) to service_role;
grant execute on function public.finish_organic_growth_job(uuid, boolean, jsonb, text, date, text, text, text) to service_role;

comment on table public.organic_growth_state is 'Persistent scheduler state and lease for the Ruka Organic Growth Engine.';
comment on table public.organic_growth_snapshots is 'Private Search Console snapshots; never exposed to the public site.';
comment on table public.organic_growth_product_signals is 'Private product intelligence derived from read-only repository analysis.';
