
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmxzryueysmzksmvpwpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJteHpyeXVleXNtemtzbXZwd3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NzUyNTQsImV4cCI6MjA1NTU1MTI1NH0.2wHuvH_nIojGsFzlsOXvGa9bxAuZF38oBej4ZHhZSto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
      },
    },
    db: {
      schema: 'public',
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Add type definition for the RPC function that's missing in the generated types
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database> {
    rpc<T = any>(
      fn: 'update_lead',
      params: { p_id: number, p_data: Record<string, any> },
      options?: { count?: null | 'exact' | 'planned' | 'estimated' }
    ): Promise<{ data: T; error: null } | { data: null; error: PostgrestError }>;
  }
}
